apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.hosts.api }}
    http:
      paths:
      - path: {{ .Values.apiGateway.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.apiGateway.name }}
            port:
              number: {{ .Values.apiGateway.containerPort }}
  - host: {{ .Values.ingress.hosts.auth }}
    http:
      paths:
      - path: {{ .Values.authentication.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.authentication.name }}
            port:
              number: {{ .Values.authentication.containerPort }}
  - host: {{ .Values.ingress.hosts.web }}
    http:
      paths:
      - path: {{ .Values.frontend.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}
            port:
              number: {{ .Values.frontend.containerPort }}
