apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: authentication-service
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: authentication-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: authentication-service
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGIN
              value: http://localhost:3000,http://localhost:4200
            - name: MONGO_COLLECTION_NAME
              value: users
            - name: MONGO_DB_NAME
              value: auth
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: PORT
              value: "3001"
            - name: RABBITMQ_HOST
              value: some-rabbit
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: SALT_ROUNDS
              value: "9"
            - name: SECRET_KEY
              value: secretkey
          image: dusanlazic/accommodatio-auth:1.0.0
          name: authentication-service
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
