apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - env:
            - name: ALLOWED_ORIGIN
              value: http://localhost:4200
            - name: MONGO_COLLECTION_NAME
              value: users
            - name: MONGO_DB_NAME
              value: users
            - name: MONGO_URI
              value: mongodb://mongo:27017
            - name: PORT
              value: "3002"
            - name: RABBITMQ_HOST
              value: some-rabbit
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
          image: dusanlazic/accommodatio-users:1.0.0
          name: user-service
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
