apiVersion: v1
kind: Service
metadata:
  labels:
    app: authentication-service
  name: authentication-service
spec:
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: authentication-service
