apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.configMapName }}
data:
  default.conf: |
    server {
        listen 80;
        server_name {{ .Values.ingress.hosts.web }};

        root /usr/share/nginx/html;
        index index.html;

        location / {
            include /etc/nginx/mime.types;
            try_files $uri $uri/ /index.html$is_args$args;
        }
    }
