apiVersion: v1
kind: Service
metadata:
  labels:
    app: accommodation-service
  name: accommodation-service
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    app: accommodation-service
