apiVersion: v1
kind: Service
metadata:
  labels:
    app: availability-service
  name: availability-service
spec:
  ports:
    - name: "3004"
      port: 3004
      targetPort: 3004
  selector:
    app: availability-service
